import { chromium } from 'playwright';
import { existsSync, readdirSync } from 'node:fs';
const root = '/opt/pw-browsers';
const dir = readdirSync(root).filter((d) => d.startsWith('chromium-')).sort().pop();
const b = await chromium.launch({ executablePath: `${root}/${dir}/chrome-linux/chrome` });
const p = await b.newPage({ viewport: { width: 1360, height: 1100 } });
await p.goto('http://localhost:4310/sign-in');
await p.fill('input[name=email]', 'mandy@grproperty.co.za');
await p.fill('input[name=password]', 'command-centre-dev-2026');
await p.click('button[type=submit]');
await p.waitForURL('http://localhost:4310/');
await p.goto('http://localhost:4310/work', { waitUntil: 'networkidle' });
await p.screenshot({ path: `${process.argv[2]}/08-work-before.png`, fullPage: true });
const btn = p.locator('button:has-text("Prepare everything for me")');
console.log('button present:', await btn.count());
await btn.click();
await p.waitForTimeout(3000);
await p.screenshot({ path: `${process.argv[2]}/09-work-after.png`, fullPage: true });
await p.goto('http://localhost:4310/', { waitUntil: 'networkidle' });
await p.screenshot({ path: `${process.argv[2]}/10-after-run.png`, fullPage: true });
console.log('done');
await b.close();
