/**
 * Downloads the two brand typefaces (latin + latin-ext subsets only) and writes
 * a self-hosted @font-face stylesheet. Self-hosting keeps the site free of
 * third-party requests, which matters both for page weight and for not handing
 * visitor IP addresses to an advertising company on an ethics platform.
 *
 * Run once, or whenever the font stack changes:  node scripts/fetch-fonts.mjs
 * The output is committed, so the site build itself never touches the network.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = resolve(ROOT, 'src/assets/fonts');
const CSS_OUT = resolve(ROOT, 'src/assets/css/fonts.css');

const SPEC =
  'family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,400;1,600' +
  '&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400';

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Only these subsets ship. Everything else is dead weight for an English-language site.
const KEEP = new Set(['latin', 'latin-ext']);

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function main() {
  const url = `https://fonts.googleapis.com/css2?${SPEC}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`);
  const css = await res.text();

  await mkdir(FONT_DIR, { recursive: true });
  await mkdir(dirname(CSS_OUT), { recursive: true });

  // Each face is preceded by a `/* subset */` comment, which is the only way to
  // tell the blocks apart before parsing the unicode-range.
  const blocks = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1);
  const out = [];
  let downloaded = 0;

  for (let i = 0; i < blocks.length; i += 2) {
    const subset = blocks[i];
    const block = blocks[i + 1];
    if (!KEEP.has(subset)) continue;

    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
    const remote = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    if (!family || !remote) continue;

    const file = `${slug(family)}-${weight}-${style}-${subset}.woff2`;
    const bin = await fetch(remote, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`Failed to fetch ${remote}: ${bin.status}`);
    await writeFile(resolve(FONT_DIR, file), Buffer.from(await bin.arrayBuffer()));
    downloaded += 1;

    out.push(
      `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('../fonts/${file}') format('woff2');\n` +
        (range ? `  unicode-range: ${range};\n` : '') +
        `}`
    );
  }

  const header =
    `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `   Cormorant Garamond and Montserrat are licensed under the SIL Open Font License 1.1.\n` +
    `   ${downloaded} faces, latin + latin-ext only. */\n\n`;

  await writeFile(CSS_OUT, header + out.join('\n\n') + '\n');
  console.log(`Fonts: ${downloaded} files written to src/assets/fonts/`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
