/**
 * Fetches exchange rates and writes them to content/data/rates.json.
 *
 * The result is committed rather than fetched at build time, for the same
 * reason the Instagram cache is: a build must not fail, or silently produce a
 * different site, because a third party was unreachable. The file carries the
 * date the rates were published, and the page shows that date, so a stale rate
 * is visible rather than quietly wrong.
 *
 * Source is the Frankfurter API, which serves the European Central Bank's
 * daily reference rates. No key, no rate limit worth worrying about, and a
 * published provenance — which matters on a site whose whole argument is that
 * a figure should be traceable.
 *
 *   npm run rates
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'content', 'data', 'rates.json');
const API = 'https://api.frankfurter.dev/v1/latest';

/**
 * Kept deliberately short. A select with thirty entries is a worse control
 * than one with twelve, and the tail of that list is currencies nobody reading
 * this site is going to pay in. ZAR first because it is home.
 */
const WANTED = [
  ['ZAR', 'South African rand', 'R'],
  ['EUR', 'Euro', '€'],
  ['GBP', 'British pound', '£'],
  ['AUD', 'Australian dollar', 'A$'],
  ['CAD', 'Canadian dollar', 'C$'],
  ['NZD', 'New Zealand dollar', 'NZ$'],
  ['CHF', 'Swiss franc', 'CHF '],
  ['SEK', 'Swedish krona', 'kr '],
  ['INR', 'Indian rupee', '₹'],
  ['SGD', 'Singapore dollar', 'S$'],
  ['JPY', 'Japanese yen', '¥'],
  ['BRL', 'Brazilian real', 'R$'],
];

async function main() {
  const symbols = WANTED.map(([code]) => code).join(',');
  const res = await fetch(`${API}?base=USD&symbols=${symbols}`, {
    headers: { accept: 'application/json' },
  });
  if (!res.ok) throw new Error(`${API} returned ${res.status}`);
  const body = await res.json();

  const missing = WANTED.filter(([code]) => body.rates[code] == null).map(([c]) => c);
  if (missing.length) throw new Error(`no rate for ${missing.join(', ')}`);

  const previous = await readFile(OUT, 'utf8').then(JSON.parse, () => null);

  const data = {
    note: 'Generated by scripts/pull-rates.mjs. Do not edit by hand. Rates are indicative only — PayPal charges in USD and the buyer’s bank sets the rate it actually applies.',
    generated: true,
    staleAfterDays: 30,
    base: 'USD',
    date: body.date,
    source: 'European Central Bank daily reference rates, via frankfurter.dev',
    sourceUrl: 'https://api.frankfurter.dev/v1/latest?base=USD',
    currencies: WANTED.map(([code, name, symbol]) => ({
      code,
      name,
      symbol,
      rate: body.rates[code],
    })),
  };

  await writeFile(OUT, JSON.stringify(data, null, 2) + '\n');

  const was = previous?.date;
  console.log(`Rates for ${data.date}${was && was !== data.date ? ` (was ${was})` : ''}`);
  for (const c of data.currencies) console.log(`  1 USD = ${c.rate} ${c.code}`);
}

main().catch((e) => {
  console.error(String(e.message ?? e));
  process.exit(1);
});
